using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HackerRankSolutions
{
//    Problem Statement
//        Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with and, the first terms will be:

//By considering the terms in the Fibonacci sequence whose values do not exceed, find the sum of the even-valued terms.

//Input Format

//First line contains  that denotes the number of test cases.This is followed by  lines, each containing an integer, .

//Constraints

//Output Format

//Print the required answer for each test case.

//Sample Input 0

//2
//10
//100
//Sample Output 0

//10
//44
    class EvenFibonacci
    {

        static void Main(String[] args)
        {
            int t = Convert.ToInt32(Console.ReadLine());
            for (int a0 = 0; a0 < t; a0++)
            {
                long n = Convert.ToInt64(Console.ReadLine());
                Console.WriteLine(SumOfEvenFibonacci(n));

            }
        }

        public static long SumOfEvenFibonacci(long N)
        {
            if (N < 2) return 0;

            long sum = 0;
            long a = 1;
            long b = 2;
            while (b <= N)
            {
                if (b % 2 == 0)
                {
                    sum += b;
                }
                long next = a + b;
                a = b;
                b = next;
            }
            return sum;
        }
    }
}
